{
 "title": "Microservices K6 Load Test",
 "tags": [
  "thesis",
  "microservices"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Application CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{container_name=\"ots_inv_service\"}",
     "legendFormat": "Inventory Service CPU %"
    },
    {
     "expr": "docker_container_cpu_usage_percent{container_name=\"ots_order_service\"}",
     "legendFormat": "Order Service CPU %"
    },
    {
     "expr": "docker_container_cpu_usage_percent{container_name=\"ots_schedule_service\"}",
     "legendFormat": "Schedule Service CPU %"
    }
   ]
  },
  {
   "title": "Application Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "docker_container_mem_usage{container_name=\"ots_inv_service\"}",
     "legendFormat": "Inventory Service RAM"
    },
    {
     "expr": "docker_container_mem_usage{container_name=\"ots_order_service\"}",
     "legendFormat": "Order Service RAM"
    },
    {
     "expr": "docker_container_mem_usage{container_name=\"ots_schedule_service\"}",
     "legendFormat": "Schedule Service RAM"
    }
   ]
  },
  {
   "title": "Infrastructure CPU Overhead (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{container_name=\"ots_ms\"}",
     "legendFormat": "PostgreSQL CPU %"
    },
    {
     "expr": "docker_container_cpu_usage_percent{container_name=\"ots_rabbitmq\"}",
     "legendFormat": "RabbitMQ CPU %"
    },
    {
     "expr": "docker_container_cpu_usage_percent{container_name=\"ots_redis\"}",
     "legendFormat": "Redis CPU %"
    },
    {
     "expr": "docker_container_cpu_usage_percent{container_name=\"ots_gateway\"}",
     "legendFormat": "Nginx Gateway CPU %"
    }
   ]
  },
  {
   "title": "Infrastructure Memory Overhead",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "docker_container_mem_usage{container_name=\"ots_ms\"}",
     "legendFormat": "PostgreSQL RAM"
    },
    {
     "expr": "docker_container_mem_usage{container_name=\"ots_rabbitmq\"}",
     "legendFormat": "RabbitMQ RAM"
    },
    {
     "expr": "docker_container_mem_usage{container_name=\"ots_redis\"}",
     "legendFormat": "Redis RAM"
    },
    {
     "expr": "docker_container_mem_usage{container_name=\"ots_gateway\"}",
     "legendFormat": "Nginx Gateway RAM"
    }
   ]
  }
 ]
}