events {}

http {
    server {
        listen 80;

        # 1. Inventory Service
        location /api/inventory/ {
    
            proxy_pass http://ots-inv:80/;
        }

        # 2. Order Service
        location /api/order/ {
    proxy_pass http://ots-order:80; 
}

        # 3. Schedule Service
        location /api/schedule/ {
            proxy_pass http://ots-schedule:80;
        }
    }
}