// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OTS_INV.Data;

#nullable disable

namespace OTS_INV.Migrations
{
    [DbContext(typeof(InvDbContext))]
    [Migration("20260412235655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OTS_INV.models.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TICKET_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TicketId"));

                    b.Property<bool>("IsSold")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_SOLD");

                    b.Property<long>("TicketClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("TICKET_CLASS_ID");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TICKET_NUMBER");

                    b.HasKey("TicketId");

                    b.HasIndex("TicketClassId");

                    b.ToTable("TICKET");
                });

            modelBuilder.Entity("OTS_INV.models.TicketClass", b =>
                {
                    b.Property<long>("TicketClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TICKET_CLASS_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TicketClassId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("CAPACITY");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("PRICE");

                    b.Property<string>("TicketClassCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TICKET_CLASS_CODE");

                    b.Property<string>("TicketClassName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("TICKET_CLASS_NAME");

                    b.HasKey("TicketClassId");

                    b.ToTable("TICKET_CLASS");
                });

            modelBuilder.Entity("OTS_INV.models.Ticket", b =>
                {
                    b.HasOne("OTS_INV.models.TicketClass", "TicketClass")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketClass");
                });

            modelBuilder.Entity("OTS_INV.models.TicketClass", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
